## THEORY QUESTIONS-
1.  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?
ANS- NumPy arrays can execute advanced mathematical operations with large data sets more efficiently and with less code than when using Python's built-in lists. This is critical for scientific computing sequence, where size and speed are vital.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?
ANS- The np. mean() method returns the arithmetic mean, but the np. average() function returns the algebraic mean if no additional parameters are specified, but it may also be used to compute a weighted average

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.
ANS- As we know Numpy is a general-purpose array-processing package that provides a high-performance multidimensional array object, and tools for working with these arrays. Let’s discuss how can we reverse a Numpy array. 

Using flip() function to Reverse a Numpy array
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

4.  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.
ANS- Checking the Data Type of NumPy Array
We can check the datatype of Numpy array by using dtype. Then it returns the data type all the elements in the array. In the given example below we import NumPy library and craete an array using “array()” method with integer value.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
ANS- An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape , which is a tuple of N non-negative integers that specify the sizes of each dimension.

6.  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
ANS- NumPy arrays are homogeneous and contiguous in memory, allowing for optimized processing with compiled C code. This results in faster execution times for mathematical operations and array manipulations compared to Python lists, particularly when dealing with large datasets or complex numerical computations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output
ANS- An HStack and a VStack are used to place other widgets in columns (HStack) or in rows (VStack). Both can be nested as much as needed to produce the desired layout.

8.  Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.
ANS- Fliplr(a) that corresponds to np. flip(a, axis=1) . flipud can only flip an array along the vertical axis and flip will flip along a given axis.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
ANS- Array_split() function allows uneven splits and handles any remaining elements. Efficiency: While numpy. split() divides the array into equal-sized sub-arrays, numpy. array_split() can handle uneven splits

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
ANS- Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations.

In [6]:
# PRACTICAL QUESTIONS -
#1 Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


import numpy as np
array = np.random.randint(low=0, high=10, size=(3, 3))



In [7]:
print(array)

[[5 8 4]
 [4 3 1]
 [0 6 0]]


In [8]:
#2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)

# Step 2: Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Step 3: Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

# Output the results
print("1D Array:", array_1d)
print("2x5 Array:\n", array_2x5)
print("5x2 Array:\n", array_5x2)


1D Array: [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
#3  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Step 2: Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Output the results
print("4x4 Array with Random Floats:\n", array_4x4)
print("6x6 Array with Border of Zeros:\n", array_with_border)


4x4 Array with Random Floats:
 [[0.15725273 0.96094746 0.02036131 0.04812244]
 [0.52299678 0.95450635 0.98118917 0.04356345]
 [0.23566588 0.55342891 0.65300163 0.19803567]
 [0.64804999 0.62303857 0.38832121 0.79287554]]
6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.15725273 0.96094746 0.02036131 0.04812244 0.        ]
 [0.         0.52299678 0.95450635 0.98118917 0.04356345 0.        ]
 [0.         0.23566588 0.55342891 0.65300163 0.19803567 0.        ]
 [0.         0.64804999 0.62303857 0.38832121 0.79287554 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [10]:
#4 Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)

# Output the result
print("Array of integers from 10 to 60 with a step of 5:\n", array)



Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


In [12]:
#5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

import numpy as np

# Step 1: Create an array of strings
strings = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
uppercase = np.array([s.upper() for s in strings])  # Uppercase
lowercase = np.array([s.lower() for s in strings])  # Lowercase
titlecase = np.array([s.title() for s in strings])  # Title case
capitalize = np.array([s.capitalize() for s in strings])  # Capitalize

# Output the results
print("Uppercase:\n", uppercase)
print("Lowercase:\n", lowercase)
print("Title Case:\n", titlecase)
print("Capitalize:\n", capitalize)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (1775961873.py, line 2)

In [13]:
#6  Generate a NumPy array of words. Insert a space between each character of every word in the array.


import numpy as np

# Step 1: Create an array of words
words = np.array(['hello', 'world', 'numpy', 'array'])

# Step 2: Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in words])

# Output the result
print("Array of words with spaces between characters:\n", spaced_words)


Array of words with spaces between characters:
 ['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [14]:
#7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Step 2: Perform element-wise operations
addition = array1 + array2           # Addition
subtraction = array1 - array2        # Subtraction
multiplication = array1 * array2     # Multiplication
division = array1 / array2           # Division

# Output the results
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)



Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [15]:
#8 Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = identity_matrix.diagonal()

# Output the results
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)



Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [16]:
#9 Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
#this array.
import numpy as np

# Step 1: Generate an array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

# Output the results
print("Random Array:", random_array)
print("Prime Numbers:", prime_numbers)




Random Array: [  8 800 851 755 206 876 383  27 704 900 549  46 392 459 382 773 702 608
 496 392 706 995 982 604 192 688 557 584 438 810 564 600 903 127 224 453
 111 356 204 493 354 244 611 891 293  45 169 821 805 662 222 939 795 825
 251 386 328 405 958 485 912 323 973 398 736 823 772  49 857 493 160 820
 584 925 528 737 938 465 170 534 859 518 804 729  24 895 766 605 473 496
 885 432  28 883 371 637 621 548 728 686]
Prime Numbers: [383, 773, 557, 127, 293, 821, 251, 823, 857, 859, 883]


In [19]:
#10 Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
#averages.
import numpy as np

# Step 1: Create an array of daily temperatures for 30 days
# For example, random temperatures between 0 and 100 degrees
daily_temperatures = np.random.randint(0, 101, size=30)

# Step 2: Reshape the array into weeks (4 full weeks and 2 extra days)
# We can make it 5 rows (weeks) and 7 columns (days), filling the last row with NaN
weekly_temperatures = np.reshape(daily_temperatures, (30, 7))

# Step 3: Calculate the weekly averages, ignoring NaN values
weekly_averages = np.nanmean(weekly_temperatures, axis=1)

# Output the results
print("Daily Temperatures for the Month:", daily_temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:", weekly_averages)



ValueError: cannot reshape array of size 30 into shape (30,7)